name: IVH
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=1.26.4
  - matplotlib=3.8.2
  - scipy=1.11.4
  - scikit-image=0.22.0
  - pydicom=2.4.4
  - streamlit=1.29.0
  - pandas=2.1.4
  - pillow=10.2.0
  - pip
  - pip:
    - opencv-python==4.9.0.80